language: python
sudo: false

matrix:
  include:
  - python: 3.8
    dist: bionic
    env: TOXENV=py38
  - python: nightly
    dist: bionic
    env: TOXENV=py39
  allow_failures:
  - env: TOXENV=py39

before_install:
  - python -m pip install --upgrade pip virtualenv setuptools

# command to install dependencies
install:
  - cd python/cdk-blank-python/
  - pip install -r requirements.txt
  - pip install -r layer/requirements.txt

# command to run tests
script:
  - cd tests/
  - chmod +x run_unittests.sh
  #- ./run_unittests.sh
